/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void StartButtonClick(GButton source, GEvent event) { //_CODE_:Start_Button:622067:
  println("button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Start_Button:622067:

public void HelpButtonClick(GButton source, GEvent event) { //_CODE_:Help_Button:677148:
  println("Help_Button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Help_Button:677148:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:MatchBox_verables:938871:
  appc.background(230);
} //_CODE_:MatchBox_verables:938871:

public void Name1_Change(GTextField source, GEvent event) { //_CODE_:Name1:726213:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:Name1:726213:

public void Name2_Change(GTextField source, GEvent event) { //_CODE_:Name2:873715:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:Name2:873715:

public void AgeSliderChange(GCustomSlider source, GEvent event) { //_CODE_:Age1:900375:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Age1:900375:

public void custom_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:Age2:887534:
  println("custom_slider2 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Age2:887534:

public void HeightSliderChange(GCustomSlider source, GEvent event) { //_CODE_:Height1:390154:
  println("custom_slider3 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Height1:390154:

public void Height2SliderChange(GCustomSlider source, GEvent event) { //_CODE_:Height2:855726:
  println("custom_slider4 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Height2:855726:

public void WeightSliderChange(GCustomSlider source, GEvent event) { //_CODE_:Weight1:803483:
  println("custom_slider5 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Weight1:803483:

public void Confirm_Click(GButton source, GEvent event) { //_CODE_:Confirm:834868:
  println("Confirm - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Confirm:834868:

public void Weight2SliderChange(GCustomSlider source, GEvent event) { //_CODE_:Weight2:986884:
  println("Weight2 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Weight2:986884:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Start_Button = new GButton(this, 210, 143, 80, 30);
  Start_Button.setText("Start");
  Start_Button.addEventHandler(this, "StartButtonClick");
  MatchBox_Title = new GLabel(this, 160, 43, 174, 68);
  MatchBox_Title.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  MatchBox_Title.setText("MatchBox");
  MatchBox_Title.setOpaque(false);
  Help_Button = new GButton(this, 210, 202, 80, 30);
  Help_Button.setText("Help");
  Help_Button.addEventHandler(this, "HelpButtonClick");
  MatchBox_verables = GWindow.getWindow(this, "Window title", 0, 0, 500, 400, JAVA2D);
  MatchBox_verables.noLoop();
  MatchBox_verables.setActionOnClose(G4P.KEEP_OPEN);
  MatchBox_verables.addDrawHandler(this, "win_draw1");
  Name1 = new GTextField(MatchBox_verables, 50, 12, 120, 30, G4P.SCROLLBARS_NONE);
  Name1.setOpaque(true);
  Name1.addEventHandler(this, "Name1_Change");
  Name2 = new GTextField(MatchBox_verables, 301, 15, 120, 30, G4P.SCROLLBARS_NONE);
  Name2.setOpaque(true);
  Name2.addEventHandler(this, "Name2_Change");
  Age1 = new GCustomSlider(MatchBox_verables, 27, 70, 150, 50, "grey_blue");
  Age1.setShowValue(true);
  Age1.setShowLimits(true);
  Age1.setLimits(1, 0, 100);
  Age1.setShowTicks(true);
  Age1.setNumberFormat(G4P.INTEGER, 0);
  Age1.setLocalColorScheme(GCScheme.RED_SCHEME);
  Age1.setOpaque(false);
  Age1.addEventHandler(this, "AgeSliderChange");
  Age2 = new GCustomSlider(MatchBox_verables, 283, 74, 150, 50, "grey_blue");
  Age2.setShowValue(true);
  Age2.setShowLimits(true);
  Age2.setLimits(1, 0, 100);
  Age2.setShowTicks(true);
  Age2.setNumberFormat(G4P.INTEGER, 0);
  Age2.setLocalColorScheme(GCScheme.RED_SCHEME);
  Age2.setOpaque(false);
  Age2.addEventHandler(this, "custom_slider2_change1");
  Height1 = new GCustomSlider(MatchBox_verables, 33, 155, 150, 50, "grey_blue");
  Height1.setShowValue(true);
  Height1.setShowLimits(true);
  Height1.setLimits(50.0, 50.0, 300.0);
  Height1.setShowTicks(true);
  Height1.setNumberFormat(G4P.DECIMAL, 2);
  Height1.setLocalColorScheme(GCScheme.RED_SCHEME);
  Height1.setOpaque(false);
  Height1.addEventHandler(this, "HeightSliderChange");
  Height2 = new GCustomSlider(MatchBox_verables, 281, 160, 150, 50, "grey_blue");
  Height2.setShowValue(true);
  Height2.setShowLimits(true);
  Height2.setLimits(50.0, 50.0, 300.0);
  Height2.setShowTicks(true);
  Height2.setNumberFormat(G4P.DECIMAL, 2);
  Height2.setLocalColorScheme(GCScheme.RED_SCHEME);
  Height2.setOpaque(false);
  Height2.addEventHandler(this, "Height2SliderChange");
  Weight1 = new GCustomSlider(MatchBox_verables, 33, 245, 150, 50, "grey_blue");
  Weight1.setShowValue(true);
  Weight1.setShowLimits(true);
  Weight1.setLimits(0.5, 0.0, 800.0);
  Weight1.setShowTicks(true);
  Weight1.setNumberFormat(G4P.DECIMAL, 2);
  Weight1.setLocalColorScheme(GCScheme.RED_SCHEME);
  Weight1.setOpaque(false);
  Weight1.addEventHandler(this, "WeightSliderChange");
  Confirm = new GButton(MatchBox_verables, 200, 290, 80, 30);
  Confirm.setText("Confirm");
  Confirm.addEventHandler(this, "Confirm_Click");
  Weight2 = new GCustomSlider(MatchBox_verables, 286, 248, 150, 50, "grey_blue");
  Weight2.setShowValue(true);
  Weight2.setShowLimits(true);
  Weight2.setLimits(0.5, 0.0, 800.0);
  Weight2.setShowTicks(true);
  Weight2.setNumberFormat(G4P.DECIMAL, 2);
  Weight2.setLocalColorScheme(GCScheme.RED_SCHEME);
  Weight2.setOpaque(false);
  Weight2.addEventHandler(this, "Weight2SliderChange");
  WeightLabel1 = new GLabel(MatchBox_verables, 18, 223, 80, 20);
  WeightLabel1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  WeightLabel1.setText("Weight");
  WeightLabel1.setOpaque(false);
  WeightLabel2 = new GLabel(MatchBox_verables, 270, 225, 80, 20);
  WeightLabel2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  WeightLabel2.setText("Weight");
  WeightLabel2.setOpaque(false);
  HeightLabel1 = new GLabel(MatchBox_verables, 17, 128, 80, 20);
  HeightLabel1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  HeightLabel1.setText("Height");
  HeightLabel1.setOpaque(false);
  HeightLabel2 = new GLabel(MatchBox_verables, 262, 138, 80, 20);
  HeightLabel2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  HeightLabel2.setText("Height");
  HeightLabel2.setOpaque(false);
  AgeLabel1 = new GLabel(MatchBox_verables, 10, 50, 80, 20);
  AgeLabel1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  AgeLabel1.setText("Age");
  AgeLabel1.setOpaque(false);
  AgeLabel2 = new GLabel(MatchBox_verables, 268, 52, 80, 20);
  AgeLabel2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  AgeLabel2.setText("Age");
  AgeLabel2.setOpaque(false);
  MatchBox_verables.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton Start_Button; 
GLabel MatchBox_Title; 
GButton Help_Button; 
GWindow MatchBox_verables;
GTextField Name1; 
GTextField Name2; 
GCustomSlider Age1; 
GCustomSlider Age2; 
GCustomSlider Height1; 
GCustomSlider Height2; 
GCustomSlider Weight1; 
GButton Confirm; 
GCustomSlider Weight2; 
GLabel WeightLabel1; 
GLabel WeightLabel2; 
GLabel HeightLabel1; 
GLabel HeightLabel2; 
GLabel AgeLabel1; 
GLabel AgeLabel2; 
