/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

<<<<<<< Updated upstream
=======
public void button1_click1(GButton source, GEvent event) { //_CODE_:Start:833638:
  println("Start - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Start:833638:

public void Help_click(GButton source, GEvent event) { //_CODE_:Help:325526:
  println("Help - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Help:325526:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:Data:703089:
  appc.background(230);
} //_CODE_:Data:703089:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:Name1:257610:
  println("Name1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:Name1:257610:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:Name2:740137:
  println("Name2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:Name2:740137:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider1:537860:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:custom_slider1:537860:


>>>>>>> Stashed changes

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
<<<<<<< Updated upstream
  surface.setTitle("MatchBox");
}
=======
  surface.setTitle("Sketch Window");
  MatchBoxTitle = new GLabel(this, 150, 5, 205, 75);
  MatchBoxTitle.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  MatchBoxTitle.setText("MatchBox");
  MatchBoxTitle.setOpaque(false);
  Start = new GButton(this, 208, 115, 80, 30);
  Start.setText("Start");
  Start.addEventHandler(this, "button1_click1");
  Help = new GButton(this, 207, 156, 80, 30);
  Help.setText("Help");
  Help.addEventHandler(this, "Help_click");
  Data = GWindow.getWindow(this, "Window title", 0, 0, 480, 320, JAVA2D);
  Data.noLoop();
  Data.setActionOnClose(G4P.KEEP_OPEN);
  Data.addDrawHandler(this, "win_draw2");
  Name1 = new GTextField(Data, 60, 22, 120, 30, G4P.SCROLLBARS_NONE);
  Name1.setOpaque(true);
  Name1.addEventHandler(this, "textfield1_change1");
  Name2 = new GTextField(Data, 290, 18, 120, 30, G4P.SCROLLBARS_NONE);
  Name2.setOpaque(true);
  Name2.addEventHandler(this, "textfield2_change1");
  custom_slider1 = new GCustomSlider(Data, 66, 70, 100, 40, "grey_blue");
  custom_slider1.setLimits(0.5, 0.0, 1.0);
  custom_slider1.setNumberFormat(G4P.DECIMAL, 2);
  custom_slider1.setOpaque(false);
  custom_slider1.addEventHandler(this, "custom_slider1_change1");
  Data.loop();
}

// Variable declarations 
// autogenerated do not edit
GLabel MatchBoxTitle; 
GButton Start; 
GButton Help; 
GWindow Data;
GTextField Name1; 
GTextField Name2; 
GCustomSlider custom_slider1; 
>>>>>>> Stashed changes
